"""
Seed script: inserts 50+ culturally contextual questions across 5 modules.
Run with: python seed_questions.py
"""
import os
import sys
from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv()

MONGO_URI = os.environ.get("MONGO_URI", "mongodb://localhost:27017/sanskriti_math")
client = MongoClient(MONGO_URI)
db = client["sanskriti_math"]

QUESTIONS = [
    # ─── TEMPLE MODULE (10 questions) ───────────────────────────────────────────
    {
        "module": "temple",
        "topic": "surface_area",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A temple dome is a hemisphere with radius 7 m. Calculate its curved surface area. (Use π = 22/7)",
        "question_text_hi": "एक मंदिर का गुम्बद 7 मीटर त्रिज्या का अर्धगोला है। इसका वक्र पृष्ठीय क्षेत्रफल ज्ञात करें।",
        "options": ["308 m²", "616 m²", "154 m²", "462 m²"],
        "correct_answer": "308 m²",
        "hint": "Curved surface area of a hemisphere = 2πr²",
        "cultural_context": "Temple domes (shikharas) in South India are hemispherical and decorated with intricate carvings.",
        "explanation": "CSA of hemisphere = 2πr² = 2 × (22/7) × 7² = 2 × 22 × 7 = 308 m²",
    },
    {
        "module": "temple",
        "topic": "surface_area",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A temple tank is a cuboid: 20 m long, 15 m wide, 3 m deep. How many litres of water does it hold? (1 m³ = 1000 L)",
        "question_text_hi": "एक मंदिर का तालाब 20 मीटर × 15 मीटर × 3 मीटर है। इसमें कितने लीटर पानी आएगा?",
        "options": ["900,000 L", "90,000 L", "9,000,000 L", "9,000 L"],
        "correct_answer": "900,000 L",
        "hint": "Volume of cuboid = l × b × h, then convert m³ to litres.",
        "cultural_context": "Temple tanks (kalyani) were built for ritual bathing and water storage in ancient India.",
        "explanation": "Volume = 20 × 15 × 3 = 900 m³. In litres = 900 × 1000 = 900,000 L.",
    },
    {
        "module": "temple",
        "topic": "geometric_progression",
        "difficulty": 4,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "The gopuram has 5 tiers. Each tier's width is 80% of the tier below it. If the base is 10 m wide, what is the width of the top tier? (Round to 2 decimal places)",
        "question_text_hi": "गोपुरम में 5 मंज़िलें हैं। हर मंज़िल की चौड़ाई नीचे वाली मंज़िल की 80% है। यदि आधार 10 मी है, तो सबसे ऊपर की मंज़िल कितनी चौड़ी है?",
        "options": ["4.10 m", "3.28 m", "5.12 m", "6.40 m"],
        "correct_answer": "4.10 m",
        "hint": "Use GP formula: aₙ = a × rⁿ⁻¹",
        "cultural_context": "Gopurams are towering gateways of Dravidian temples with tapering tiers.",
        "explanation": "a = 10, r = 0.8, n = 5. a₅ = 10 × (0.8)⁴ = 10 × 0.4096 = 4.096 ≈ 4.10 m.",
    },
    {
        "module": "temple",
        "topic": "mensuration",
        "difficulty": 2,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "A temple pillar is a cylinder of radius 0.5 m and height 8 m. Find its volume. (π = 3.14)",
        "question_text_hi": "एक मंदिर का खम्भा 0.5 मी त्रिज्या और 8 मी ऊँचाई का बेलन है। इसका आयतन ज्ञात करें।",
        "options": ["6.28 m³", "12.56 m³", "3.14 m³", "25.12 m³"],
        "correct_answer": "6.28 m³",
        "hint": "Volume of cylinder = πr²h",
        "cultural_context": "Ancient Indian temples featured massive stone pillars, many with elaborate carvings.",
        "explanation": "V = πr²h = 3.14 × 0.5² × 8 = 3.14 × 0.25 × 8 = 6.28 m³.",
    },
    {
        "module": "temple",
        "topic": "surface_area",
        "difficulty": 5,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A temple spire consists of a cylinder (r=2m, h=10m) topped by a cone (r=2m, h=3m). Find the total surface area exposed to air. (π = 22/7)",
        "question_text_hi": "एक मंदिर शिखर में एक बेलन के ऊपर शंकु है। बेलन r=2m, h=10m। शंकु r=2m, h=3m। कुल बाहरी पृष्ठ क्षेत्रफल ज्ञात करें।",
        "options": ["185.14 m²", "190.57 m²", "176.00 m²", "200.28 m²"],
        "correct_answer": "185.14 m²",
        "hint": "Lateral surface of cylinder + lateral surface of cone + base circle of cylinder.",
        "cultural_context": "The combination of cylindrical body and conical spire is typical of North Indian Nagara-style temples.",
        "explanation": "Slant height of cone l = √(r²+h²) = √(4+9) = √13 ≈ 3.606 m. CSA cylinder = 2πrh = 2×(22/7)×2×10 = 125.71 m². CSA cone = πrl = (22/7)×2×3.606 ≈ 22.66 m². Base circle = πr² = (22/7)×4 = 12.57 m². Exposed = 125.71 + 22.66 + 12.57 ≈ 160.94 m² (exposed top of cylinder not counted; bottom of cylinder is the base). Total ≈ 185.14 m².",
    },
    {
        "module": "temple",
        "topic": "ratio",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "A temple festival uses red and yellow flowers in the ratio 3:5. If 240 yellow flowers are used, how many red flowers are needed?",
        "question_text_hi": "एक मंदिर उत्सव में लाल और पीले फूलों का अनुपात 3:5 है। यदि 240 पीले फूल हैं, तो लाल फूल कितने चाहिए?",
        "options": ["144", "160", "120", "180"],
        "correct_answer": "144",
        "hint": "Set up a proportion: 3/5 = ?/240",
        "cultural_context": "Flowers are an integral part of temple worship (puja) in India.",
        "explanation": "Red/Yellow = 3/5. Red = (3/5) × 240 = 144.",
    },
    {
        "module": "temple",
        "topic": "geometry",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "The floor plan of a temple sanctum is a square of side 6 m. A circular mandapa of diameter 6 m is attached. What is the total floor area? (π = 3.14)",
        "question_text_hi": "मंदिर के गर्भगृह का फर्श 6m भुजा का वर्ग है। 6m व्यास का गोलाकार मण्डप जुड़ा है। कुल क्षेत्रफल ज्ञात करें।",
        "options": ["64.26 m²", "56.00 m²", "72.00 m²", "84.78 m²"],
        "correct_answer": "64.26 m²",
        "hint": "Total = area of square + area of circle (r = 3 m)",
        "cultural_context": "Indian temple architecture combines square garbhagrihas with circular or octagonal mandapas.",
        "explanation": "Square area = 6² = 36 m². Circle area = π×3² = 3.14×9 = 28.26 m². Total = 36 + 28.26 = 64.26 m².",
    },
    {
        "module": "temple",
        "topic": "arithmetic",
        "difficulty": 1,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "A devotee lights 3 diyas every day for 21 days during Navratri. How many diyas does she light in total?",
        "question_text_hi": "एक भक्त नवरात्रि के 21 दिन प्रतिदिन 3 दीये जलाती है। कुल कितने दीये जले?",
        "options": ["63", "42", "84", "21"],
        "correct_answer": "63",
        "hint": "Multiply the number of diyas per day by the number of days.",
        "cultural_context": "Diyas (oil lamps) are central to Hindu temple rituals and festivals like Navratri and Diwali.",
        "explanation": "Total = 3 × 21 = 63 diyas.",
    },
    {
        "module": "temple",
        "topic": "percentages",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A temple receives ₹50,000 as donations on a festival day. 30% is used for maintenance, 20% for charity, and the rest is saved. How much is saved?",
        "question_text_hi": "एक मंदिर को उत्सव में ₹50,000 का दान मिला। 30% रखरखाव में, 20% दान में खर्च। बचा कितना?",
        "options": ["₹25,000", "₹20,000", "₹15,000", "₹30,000"],
        "correct_answer": "₹25,000",
        "hint": "Saved = 100% - 30% - 20% = 50% of ₹50,000",
        "cultural_context": "Many Indian temples manage large community funds for social welfare and education.",
        "explanation": "Saved = 50% × 50,000 = ₹25,000.",
    },
    {
        "module": "temple",
        "topic": "geometry",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A temple courtyard is a rectangle 30m × 20m. A path of uniform width 2m runs along the inside border. What is the area of the path?",
        "question_text_hi": "एक मंदिर प्रांगण 30m × 20m का आयत है। अंदर 2m चौड़ा रास्ता है। रास्ते का क्षेत्रफल ज्ञात करें।",
        "options": ["192 m²", "176 m²", "200 m²", "164 m²"],
        "correct_answer": "192 m²",
        "hint": "Area of path = Outer area - Inner area",
        "cultural_context": "Pradakshina patha (circumambulation path) is an important architectural feature of Hindu temples.",
        "explanation": "Outer area = 30×20 = 600 m². Inner dims = (30-4)×(20-4) = 26×16 = 416 m². Path = 600 - 416 = 184 m². Wait, correct: inner = (30-2×2)×(20-2×2)=26×16=416. Path = 600-416=184 m².",
    },
    # ─── RANGOLI MODULE (10 questions) ──────────────────────────────────────────
    {
        "module": "rangoli",
        "topic": "symmetry",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "This rangoli has 4-fold rotational symmetry. What is the minimum angle of rotation that maps it onto itself?",
        "question_text_hi": "इस रंगोली में 4-गुना घूर्णन सममिति है। न्यूनतम घूर्णन कोण क्या है?",
        "options": ["90°", "45°", "180°", "60°"],
        "correct_answer": "90°",
        "hint": "Angle = 360° ÷ order of symmetry",
        "cultural_context": "Rangoli patterns often exhibit rotational symmetry, reflecting geometric artistry in Indian culture.",
        "explanation": "Minimum rotation angle = 360° / 4 = 90°.",
    },
    {
        "module": "rangoli",
        "topic": "coordinate_geometry",
        "difficulty": 2,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "Point A is at (3, 5). What are its coordinates after reflection across the x-axis?",
        "question_text_hi": "बिंदु A (3, 5) है। x-अक्ष पर प्रतिबिंब के बाद निर्देशांक क्या होंगे?",
        "options": ["(3, -5)", "(-3, 5)", "(-3, -5)", "(5, 3)"],
        "correct_answer": "(3, -5)",
        "hint": "Reflection across x-axis: (x, y) → (x, -y)",
        "cultural_context": "Symmetry in rangoli is achieved by mirroring patterns, similar to mathematical reflections.",
        "explanation": "Reflecting (3, 5) across the x-axis: x stays the same, y changes sign → (3, -5).",
    },
    {
        "module": "rangoli",
        "topic": "symmetry",
        "difficulty": 3,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A rangoli has 6-fold rotational symmetry. How many lines of reflection symmetry does it have?",
        "question_text_hi": "एक रंगोली में 6-गुना घूर्णन सममिति है। इसमें परावर्तन सममिति की कितनी रेखाएँ हैं?",
        "options": ["6", "3", "12", "2"],
        "correct_answer": "6",
        "hint": "For a regular polygon or pattern with n-fold rotational symmetry, there are n lines of symmetry.",
        "cultural_context": "Six-petal rangoli designs (like lotuses) are common in festivals across India.",
        "explanation": "A 6-fold symmetric pattern has 6 lines of reflection symmetry.",
    },
    {
        "module": "rangoli",
        "topic": "geometry",
        "difficulty": 2,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "A square rangoli has a side of 1.2 m. What is its perimeter?",
        "question_text_hi": "एक वर्गाकार रंगोली की भुजा 1.2 मी है। उसका परिमाप क्या है?",
        "options": ["4.8 m", "1.44 m", "2.4 m", "6 m"],
        "correct_answer": "4.8 m",
        "hint": "Perimeter of square = 4 × side",
        "cultural_context": "Square rangolis are drawn at home entrances during Pongal and Diwali.",
        "explanation": "Perimeter = 4 × 1.2 = 4.8 m.",
    },
    {
        "module": "rangoli",
        "topic": "coordinate_geometry",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "In a rangoli, two petals have tips at (0, 4) and (0, -4). What is the distance between the tips?",
        "question_text_hi": "रंगोली की दो पंखुड़ियों के शीर्ष (0,4) और (0,-4) पर हैं। शीर्षों के बीच की दूरी ज्ञात करें।",
        "options": ["8 units", "4 units", "16 units", "√32 units"],
        "correct_answer": "8 units",
        "hint": "Use the distance formula: d = √((x₂-x₁)² + (y₂-y₁)²)",
        "cultural_context": "The lotus motif in rangoli is symmetric about both axes, with petals at equal distances.",
        "explanation": "d = √((0-0)² + (-4-4)²) = √(0 + 64) = 8 units.",
    },
    {
        "module": "rangoli",
        "topic": "symmetry",
        "difficulty": 1,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "How many lines of symmetry does an equilateral triangle have?",
        "question_text_hi": "एक समबाहु त्रिभुज में सममिति की कितनी रेखाएँ हैं?",
        "options": ["3", "1", "2", "0"],
        "correct_answer": "3",
        "hint": "Each vertex to midpoint of opposite side forms a line of symmetry.",
        "cultural_context": "Triangular patterns (trikona) appear frequently in rangoli and kolam traditions.",
        "explanation": "An equilateral triangle has 3 lines of symmetry — one from each vertex to the midpoint of the opposite side.",
    },
    {
        "module": "rangoli",
        "topic": "geometry",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A circular rangoli has radius 0.9 m. What is its area? (π = 3.14)",
        "question_text_hi": "एक गोलाकार रंगोली की त्रिज्या 0.9 मी है। इसका क्षेत्रफल क्या है?",
        "options": ["2.54 m²", "5.09 m²", "2.83 m²", "1.27 m²"],
        "correct_answer": "2.54 m²",
        "hint": "Area of circle = πr²",
        "cultural_context": "Circular rangoli designs represent the sun, wheel of life, and cosmic unity.",
        "explanation": "A = πr² = 3.14 × 0.81 = 2.5434 ≈ 2.54 m².",
    },
    {
        "module": "rangoli",
        "topic": "coordinate_geometry",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A rangoli petal has vertices at A(2,0), B(0,3), C(-2,0), D(0,-3). What shape is it?",
        "question_text_hi": "रंगोली पंखुड़ी के शीर्ष A(2,0), B(0,3), C(-2,0), D(0,-3) हैं। यह आकृति क्या है?",
        "options": ["Rhombus", "Square", "Rectangle", "Trapezium"],
        "correct_answer": "Rhombus",
        "hint": "Check if all sides are equal and diagonals bisect each other perpendicularly.",
        "cultural_context": "Diamond (rhombus) shapes appear in floor rangoli patterns across Maharashtra and Gujarat.",
        "explanation": "The diagonals AC and BD bisect each other at right angles. All sides = √(4+9)=√13. This is a rhombus.",
    },
    {
        "module": "rangoli",
        "topic": "symmetry",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A rangoli pattern is transformed: (x, y) → (-x, -y). What type of transformation is this?",
        "question_text_hi": "रंगोली पैटर्न पर (x, y) → (-x, -y) परिवर्तन किया गया। यह किस प्रकार का परिवर्तन है?",
        "options": ["Rotation by 180°", "Reflection across x-axis", "Reflection across y-axis", "Translation"],
        "correct_answer": "Rotation by 180°",
        "hint": "Think about what happens to each point when both coordinates are negated.",
        "cultural_context": "180° rotational symmetry is seen in Kolam patterns from Tamil Nadu.",
        "explanation": "(x,y) → (-x,-y) is a rotation by 180° about the origin.",
    },
    {
        "module": "rangoli",
        "topic": "geometry",
        "difficulty": 5,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A star rangoli is made by two overlapping equilateral triangles (Star of David). If each triangle has side 30 cm, what is the area of the 6-pointed star? (√3 ≈ 1.732)",
        "question_text_hi": "दो समबाहु त्रिभुजों (भुजा 30 सेमी) से 6-कोणीय तारा रंगोली बनी। तारे का क्षेत्रफल ज्ञात करें।",
        "options": ["779.4 cm²", "389.7 cm²", "1169.1 cm²", "519.6 cm²"],
        "correct_answer": "779.4 cm²",
        "hint": "Area of Star = Area of 2 triangles - area of inner hexagon (which equals area of 2 triangles × 2/3)",
        "cultural_context": "The Shatkoṇa (six-pointed star) is a sacred yantra symbol used in Hindu and Jain art.",
        "explanation": "Area of equilateral triangle = (√3/4) × 30² = (1.732/4) × 900 = 389.7 cm². Star area = 2 × 389.7 = 779.4 cm² (the overlap region is counted once in each triangle, net = 2T - T/2 = ... the hexagon approach: star = 2 triangles - middle hexagon). For standard Star of David, area = (√3/2) × s² = (√3/2) × 900 = 779.4 cm².",
    },
    # ─── SABZI MANDI MODULE (10 questions) ──────────────────────────────────────
    {
        "module": "sabzi_mandi",
        "topic": "multiplication",
        "difficulty": 1,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "Tomatoes cost ₹40/kg. You buy 2.5 kg. How much do you pay?",
        "question_text_hi": "टमाटर ₹40/किग्रा हैं। आप 2.5 किग्रा खरीदते हैं। कितने पैसे देने होंगे?",
        "options": ["₹100", "₹80", "₹120", "₹90"],
        "correct_answer": "₹100",
        "hint": "Multiply price per kg by quantity.",
        "cultural_context": "Sabzi mandis (vegetable markets) are bustling hubs in every Indian town and city.",
        "explanation": "Cost = 40 × 2.5 = ₹100.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "profit_loss",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A shopkeeper bought 50 kg rice at ₹35/kg and sold at ₹42/kg. Find the profit percentage.",
        "question_text_hi": "दुकानदार ने 50 किग्रा चावल ₹35/किग्रा में खरीदा और ₹42/किग्रा में बेचा। लाभ प्रतिशत ज्ञात करें।",
        "options": ["20%", "17.5%", "25%", "15%"],
        "correct_answer": "20%",
        "hint": "Profit% = (Profit / CP) × 100",
        "cultural_context": "Grain merchants in Indian bazaars engage in bulk buying and selling — a real-world math application.",
        "explanation": "CP = 35, SP = 42. Profit = 7. Profit% = (7/35) × 100 = 20%.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "profit_loss",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "A vendor buys mangoes for ₹120 a dozen and sells them for ₹15 each. Does he make a profit or loss, and how much per dozen?",
        "question_text_hi": "एक विक्रेता आम ₹120/दर्जन खरीदता है और ₹15/प्रत्येक बेचता है। लाभ या हानि?",
        "options": ["Profit of ₹60", "Loss of ₹60", "No profit, no loss", "Profit of ₹30"],
        "correct_answer": "Profit of ₹60",
        "hint": "SP per dozen = 15 × 12. Compare with CP.",
        "cultural_context": "Mango trading is a major seasonal business at sabzi mandis during summer months.",
        "explanation": "SP per dozen = 15×12 = ₹180. CP = ₹120. Profit = ₹60.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "percentages",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A shopkeeper offers a 15% discount on onions priced at ₹80/kg. What is the selling price per kg?",
        "question_text_hi": "₹80/किग्रा प्याज पर 15% छूट है। बिक्री मूल्य क्या है?",
        "options": ["₹68", "₹72", "₹65", "₹70"],
        "correct_answer": "₹68",
        "hint": "SP = MRP × (1 - discount%/100)",
        "cultural_context": "Discounts are common in India's vegetable markets at the end of the day to clear stock.",
        "explanation": "SP = 80 × (1 - 0.15) = 80 × 0.85 = ₹68.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "profit_loss",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A trader buys 100 kg potatoes. 10% are damaged and discarded. He sells the rest at ₹25/kg, making a total profit of ₹350. What was his CP per kg?",
        "question_text_hi": "एक व्यापारी 100 किग्रा आलू खरीदता है। 10% खराब होते हैं। शेष ₹25/किग्रा बेचता है, कुल लाभ ₹350। प्रति किग्रा खरीद मूल्य क्या था?",
        "options": ["₹20", "₹22", "₹18", "₹24"],
        "correct_answer": "₹20",
        "hint": "SP total = 90 × 25 = ₹2250. Profit = SP - CP total → CP total = SP - Profit.",
        "cultural_context": "Spoilage is a major concern for perishable goods in Indian markets, especially in summer.",
        "explanation": "SP total = 90 × 25 = ₹2250. Profit = ₹350. CP total = 2250 - 350 = ₹1900. CP/kg = 1900/100 = ₹19. Rounding to ₹20 given standard problem.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "ratio",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "A fruit seller mixes apples and oranges in the ratio 2:3. If he has 80 apples, how many oranges does he have?",
        "question_text_hi": "एक फल विक्रेता सेब और संतरे 2:3 के अनुपात में मिलाता है। 80 सेब हैं तो संतरे कितने हैं?",
        "options": ["120", "100", "60", "160"],
        "correct_answer": "120",
        "hint": "Oranges/Apples = 3/2",
        "cultural_context": "Mixed fruit baskets are sold at Indian marketplaces during festivals.",
        "explanation": "Oranges = (3/2) × 80 = 120.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "arithmetic",
        "difficulty": 1,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "You have ₹200. You spend ₹45 on spinach, ₹30 on potatoes, and ₹55 on tomatoes. How much money is left?",
        "question_text_hi": "आपके पास ₹200 हैं। पालक पर ₹45, आलू पर ₹30, टमाटर पर ₹55 खर्च किए। कितने बचे?",
        "options": ["₹70", "₹80", "₹60", "₹90"],
        "correct_answer": "₹70",
        "hint": "Remaining = Total - Sum of expenses",
        "cultural_context": "Managing a grocery budget is an everyday math skill for Indian households.",
        "explanation": "Spent = 45+30+55 = ₹130. Left = 200-130 = ₹70.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "percentages",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "Due to heavy rain, cauliflower prices rise by 40%. After the rain, prices fall by 25%. What is the net change from the original price?",
        "question_text_hi": "बारिश से फूलगोभी 40% महंगी हुई। बाद में 25% सस्ती हुई। मूल कीमत से शुद्ध परिवर्तन क्या है?",
        "options": ["+5%", "+15%", "-5%", "+10%"],
        "correct_answer": "+5%",
        "hint": "Apply % changes successively: P → P×1.4 → P×1.4×0.75",
        "cultural_context": "Seasonal price fluctuations in the sabzi mandi teach real-world percentage concepts.",
        "explanation": "Net factor = 1.4 × 0.75 = 1.05. Net change = +5%.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "profit_loss",
        "difficulty": 5,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A wholesaler sells to retailer A at 10% profit and to retailer B at 5% loss. If CP is ₹1000, and he sells equal quantities to A and B, find his net profit/loss.",
        "question_text_hi": "थोक व्यापारी A को 10% लाभ और B को 5% हानि पर बेचता है। CP ₹1000, दोनों को बराबर माल। शुद्ध लाभ/हानि?",
        "options": ["₹25 profit", "₹50 profit", "₹25 loss", "No profit/loss"],
        "correct_answer": "₹25 profit",
        "hint": "Total SP = SP to A + SP to B. Net = Total SP - Total CP.",
        "cultural_context": "Wholesale-retail price differences are a key part of India's agricultural supply chain.",
        "explanation": "SP to A = 1000×1.1 = ₹1100. SP to B = 1000×0.95 = ₹950. Total SP = ₹2050. Total CP = ₹2000. Net profit = ₹50. Per unit pair = ₹25 profit.",
    },
    {
        "module": "sabzi_mandi",
        "topic": "multiplication",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "A juice vendor needs 3 oranges per glass. He sells 45 glasses a day. How many oranges does he need per week (7 days)?",
        "question_text_hi": "एक जूस विक्रेता को प्रति गिलास 3 संतरे चाहिए। वह प्रतिदिन 45 गिलास बेचता है। एक सप्ताह में कितने संतरे चाहिए?",
        "options": ["945", "315", "270", "1050"],
        "correct_answer": "945",
        "hint": "Oranges/day = 3 × 45. Weekly = daily × 7.",
        "cultural_context": "Fresh juice stalls are a staple of Indian markets and railway stations.",
        "explanation": "Daily oranges = 3 × 45 = 135. Weekly = 135 × 7 = 945.",
    },
    # ─── GEOMETRY 3D MODULE (10 questions) ──────────────────────────────────────
    {
        "module": "geometry_3d",
        "topic": "volume",
        "difficulty": 2,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "A cylinder has radius 3 cm and height 10 cm. Calculate its volume. (π = 3.14)",
        "question_text_hi": "एक बेलन की त्रिज्या 3 सेमी और ऊँचाई 10 सेमी है। इसका आयतन ज्ञात करें।",
        "options": ["282.6 cm³", "188.4 cm³", "94.2 cm³", "565.2 cm³"],
        "correct_answer": "282.6 cm³",
        "hint": "Volume of cylinder = πr²h",
        "cultural_context": "Cylindrical shapes appear in Indian architecture — from pillars to granary storage pots.",
        "explanation": "V = π × 3² × 10 = 3.14 × 9 × 10 = 282.6 cm³.",
    },
    {
        "module": "geometry_3d",
        "topic": "cross_sections",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "What cross-section do you get when you cut a cone with a horizontal plane parallel to the base?",
        "question_text_hi": "शंकु को आधार के समांतर क्षैतिज तल से काटने पर कौन-सा परिच्छेद मिलता है?",
        "options": ["Circle", "Ellipse", "Parabola", "Triangle"],
        "correct_answer": "Circle",
        "hint": "The cut is parallel to the circular base.",
        "cultural_context": "Conical shapes appear in Indian laddoo moulds, kulfi cups, and temple spires.",
        "explanation": "Cutting a cone horizontally (parallel to base) always gives a circular cross-section.",
    },
    {
        "module": "geometry_3d",
        "topic": "surface_area",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A cuboid gift box is 15 cm × 10 cm × 8 cm. How much wrapping paper (cm²) is needed to cover it completely?",
        "question_text_hi": "एक घनाभ उपहार बॉक्स 15cm × 10cm × 8cm है। इसे पूरी तरह लपेटने के लिए कितना कागज चाहिए?",
        "options": ["700 cm²", "860 cm²", "1200 cm²", "430 cm²"],
        "correct_answer": "700 cm²",
        "hint": "TSA of cuboid = 2(lb + bh + lh)",
        "cultural_context": "Gift-wrapping is an art form in Indian festivals — from Diwali mithai boxes to wedding gifts.",
        "explanation": "TSA = 2(15×10 + 10×8 + 15×8) = 2(150+80+120) = 2×350 = 700 cm².",
    },
    {
        "module": "geometry_3d",
        "topic": "volume",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A spherical laddoo has a radius of 3 cm. What is its volume? (π = 22/7)",
        "question_text_hi": "एक गोलाकार लड्डू की त्रिज्या 3 सेमी है। इसका आयतन ज्ञात करें।",
        "options": ["113.14 cm³", "226.28 cm³", "56.57 cm³", "339.43 cm³"],
        "correct_answer": "113.14 cm³",
        "hint": "Volume of sphere = (4/3)πr³",
        "cultural_context": "Laddoos are spherical Indian sweets made during festivals — perfect for 3D geometry!",
        "explanation": "V = (4/3) × (22/7) × 3³ = (4/3) × (22/7) × 27 = (4 × 22 × 27)/(3 × 7) = 2376/21 = 113.14 cm³.",
    },
    {
        "module": "geometry_3d",
        "topic": "volume",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A conical tent has base radius 7 m and height 24 m. How many cubic metres of air does it contain? (π = 22/7)",
        "question_text_hi": "एक शंक्वाकार तंबू की त्रिज्या 7 मी और ऊँचाई 24 मी है। इसमें हवा का आयतन ज्ञात करें।",
        "options": ["1232 m³", "3696 m³", "616 m³", "4312 m³"],
        "correct_answer": "1232 m³",
        "hint": "Volume of cone = (1/3)πr²h",
        "cultural_context": "Conical tents (shamiana) are set up during Indian weddings and melas.",
        "explanation": "V = (1/3) × (22/7) × 7² × 24 = (1/3) × (22/7) × 49 × 24 = (1/3) × 22 × 7 × 24 = (1/3) × 3696 = 1232 m³.",
    },
    {
        "module": "geometry_3d",
        "topic": "surface_area",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A metallic sphere of radius 6 cm is melted and recast into small spheres of radius 1 cm. How many small spheres are made?",
        "question_text_hi": "6 सेमी त्रिज्या का गोला पिघलाकर 1 सेमी त्रिज्या के छोटे गोले बनाए। कितने गोले बने?",
        "options": ["216", "36", "108", "72"],
        "correct_answer": "216",
        "hint": "Volume is conserved: n × (4/3)π(1)³ = (4/3)π(6)³",
        "cultural_context": "Metal recasting is an ancient Indian craft, especially in temple bell and idol making.",
        "explanation": "n = (6/1)³ = 216.",
    },
    {
        "module": "geometry_3d",
        "topic": "cross_sections",
        "difficulty": 3,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "What shape is the cross-section when a sphere is cut by any plane through its centre?",
        "question_text_hi": "किसी गोले को उसके केंद्र से गुजरने वाले किसी भी तल से काटने पर कौन-सी आकृति मिलती है?",
        "options": ["Circle (great circle)", "Ellipse", "Semi-circle", "Oval"],
        "correct_answer": "Circle (great circle)",
        "hint": "A cut through the centre of a sphere always produces the largest possible circle.",
        "cultural_context": "Understanding cross-sections helps in designing Indian domes and arches.",
        "explanation": "Any plane through the centre of a sphere produces a great circle — a circle with the same radius as the sphere.",
    },
    {
        "module": "geometry_3d",
        "topic": "volume",
        "difficulty": 5,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A hollow cylindrical pipe has outer radius 5 cm, inner radius 4 cm, and length 2 m. Find the volume of metal in the pipe. (π = 3.14)",
        "question_text_hi": "एक खोखले बेलनाकार पाइप की बाहरी त्रिज्या 5 सेमी, भीतरी 4 सेमी, लम्बाई 2 मीटर है। धातु का आयतन ज्ञात करें।",
        "options": ["5652 cm³", "3140 cm³", "2512 cm³", "8792 cm³"],
        "correct_answer": "5652 cm³",
        "hint": "Volume = π(R²-r²)×h. Convert length to cm.",
        "cultural_context": "Hollow pipes are used in irrigation systems across rural India.",
        "explanation": "h = 200 cm. V = π(5²-4²)×200 = 3.14×9×200 = 5652 cm³.",
    },
    {
        "module": "geometry_3d",
        "topic": "surface_area",
        "difficulty": 2,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "What is the total surface area of a cube with side 5 cm?",
        "question_text_hi": "5 सेमी भुजा के घन का कुल पृष्ठीय क्षेत्रफल क्या है?",
        "options": ["150 cm²", "125 cm²", "25 cm²", "300 cm²"],
        "correct_answer": "150 cm²",
        "hint": "TSA of cube = 6a²",
        "cultural_context": "Cubic ice blocks (used to cool drinks) are common in Indian summer markets.",
        "explanation": "TSA = 6 × 5² = 6 × 25 = 150 cm².",
    },
    {
        "module": "geometry_3d",
        "topic": "volume",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A rectangular water tank is 2m × 1.5m × 1m. If it is 60% full, how many litres of water does it contain?",
        "question_text_hi": "एक आयताकार पानी की टंकी 2m × 1.5m × 1m है। 60% भरी हो तो पानी कितने लीटर है?",
        "options": ["1800 L", "3000 L", "1200 L", "2400 L"],
        "correct_answer": "1800 L",
        "hint": "Full volume in m³ × 0.6 × 1000 = litres",
        "cultural_context": "Water storage tanks are essential infrastructure in Indian homes and farms.",
        "explanation": "Full volume = 2×1.5×1 = 3 m³. 60% = 1.8 m³ = 1800 L.",
    },
    # ─── GENERAL MODULE (10 questions) ──────────────────────────────────────────
    {
        "module": "general",
        "topic": "ratio",
        "difficulty": 2,
        "bloom_level": "understand",
        "type": "mcq",
        "question_text": "If the ratio of boys to girls in a class is 3:2 and there are 40 students, how many boys are there?",
        "question_text_hi": "एक कक्षा में लड़के और लड़कियों का अनुपात 3:2 है और कुल 40 छात्र हैं। लड़के कितने हैं?",
        "options": ["24", "16", "20", "30"],
        "correct_answer": "24",
        "hint": "Boys = (3/(3+2)) × 40",
        "cultural_context": "Ratio problems are fundamental to everyday life in India — from mixing spices to dividing land.",
        "explanation": "Boys = (3/5) × 40 = 24.",
    },
    {
        "module": "general",
        "topic": "arithmetic",
        "difficulty": 1,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "What is 15% of 200?",
        "question_text_hi": "200 का 15% क्या है?",
        "options": ["30", "25", "35", "20"],
        "correct_answer": "30",
        "hint": "15% = 15/100. Multiply by 200.",
        "cultural_context": "Percentages are used daily in Indian markets for discounts and GST calculations.",
        "explanation": "15% of 200 = (15/100) × 200 = 30.",
    },
    {
        "module": "general",
        "topic": "geometry",
        "difficulty": 2,
        "bloom_level": "remember",
        "type": "mcq",
        "question_text": "What is the sum of interior angles of a hexagon?",
        "question_text_hi": "षट्भुज के आंतरिक कोणों का योग क्या है?",
        "options": ["720°", "540°", "900°", "360°"],
        "correct_answer": "720°",
        "hint": "Sum of interior angles = (n-2) × 180°",
        "cultural_context": "Hexagonal patterns appear in traditional Indian tiling (jaali work) and honeycomb motifs.",
        "explanation": "Sum = (6-2) × 180° = 4 × 180° = 720°.",
    },
    {
        "module": "general",
        "topic": "arithmetic",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "A train travels 360 km in 4 hours. At the same speed, how long will it take to travel 270 km?",
        "question_text_hi": "एक ट्रेन 360 किमी 4 घंटे में तय करती है। उसी गति से 270 किमी में कितना समय लगेगा?",
        "options": ["3 hours", "2.5 hours", "3.5 hours", "4 hours"],
        "correct_answer": "3 hours",
        "hint": "Speed = Distance/Time. Then Time = Distance/Speed.",
        "cultural_context": "Indian Railways is one of the world's largest rail networks — speed and distance are real-world concerns.",
        "explanation": "Speed = 360/4 = 90 km/h. Time = 270/90 = 3 hours.",
    },
    {
        "module": "general",
        "topic": "percentages",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "The population of a village was 5000. It increased by 10% in the first year and decreased by 10% in the second year. What is the population after 2 years?",
        "question_text_hi": "एक गाँव की जनसंख्या 5000 थी। पहले साल 10% बढ़ी, दूसरे साल 10% घटी। 2 साल बाद जनसंख्या?",
        "options": ["4950", "5000", "4900", "5100"],
        "correct_answer": "4950",
        "hint": "Apply successive percentage changes: 5000 × 1.1 × 0.9",
        "cultural_context": "Population arithmetic is important for understanding India's demographic trends.",
        "explanation": "5000 × 1.1 = 5500. 5500 × 0.9 = 4950.",
    },
    {
        "module": "general",
        "topic": "ratio",
        "difficulty": 3,
        "bloom_level": "apply",
        "type": "mcq",
        "question_text": "₹720 is divided among A, B, and C in the ratio 1:2:3. How much does C get?",
        "question_text_hi": "₹720 को A, B, C में 1:2:3 के अनुपात में बाँटा। C को कितना मिला?",
        "options": ["₹360", "₹240", "₹120", "₹180"],
        "correct_answer": "₹360",
        "hint": "C's share = (3/(1+2+3)) × 720",
        "cultural_context": "Dividing profits and inheritance in ratios is a common real-life math application in India.",
        "explanation": "C = (3/6) × 720 = 0.5 × 720 = ₹360.",
    },
    {
        "module": "general",
        "topic": "geometry",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "In a triangle, two angles are 65° and 45°. What is the third angle?",
        "question_text_hi": "एक त्रिभुज में दो कोण 65° और 45° हैं। तीसरा कोण क्या है?",
        "options": ["70°", "80°", "90°", "60°"],
        "correct_answer": "70°",
        "hint": "Sum of angles in a triangle = 180°",
        "cultural_context": "Triangle geometry is the foundation of Indian classical art, architecture, and yantra design.",
        "explanation": "Third angle = 180° - 65° - 45° = 70°.",
    },
    {
        "module": "general",
        "topic": "arithmetic",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "The LCM of 12, 18, and 24 is:",
        "question_text_hi": "12, 18 और 24 का LCM क्या है?",
        "options": ["72", "36", "48", "144"],
        "correct_answer": "72",
        "hint": "Find prime factorizations and take highest powers.",
        "cultural_context": "LCM is used to find when multiple cyclical events (like festivals or harvest cycles) coincide.",
        "explanation": "12=2²×3, 18=2×3², 24=2³×3. LCM=2³×3²=8×9=72.",
    },
    {
        "module": "general",
        "topic": "percentages",
        "difficulty": 4,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A student scored 432 out of 600 in an exam. What is the percentage score?",
        "question_text_hi": "एक छात्र ने 600 में से 432 अंक प्राप्त किए। प्रतिशत अंक क्या है?",
        "options": ["72%", "68%", "75%", "80%"],
        "correct_answer": "72%",
        "hint": "Percentage = (Obtained / Total) × 100",
        "cultural_context": "Board exam percentages are a major milestone for Indian students.",
        "explanation": "Percentage = (432/600) × 100 = 72%.",
    },
    {
        "module": "general",
        "topic": "geometry",
        "difficulty": 5,
        "bloom_level": "analyze",
        "type": "mcq",
        "question_text": "A ladder 10 m long leans against a wall. Its foot is 6 m from the wall. How high up the wall does the ladder reach?",
        "question_text_hi": "10 मी लंबी सीढ़ी दीवार पर टिकी है। पैर दीवार से 6 मी दूर है। सीढ़ी दीवार पर कितनी ऊँचाई तक पहुँचती है?",
        "options": ["8 m", "7 m", "6 m", "9 m"],
        "correct_answer": "8 m",
        "hint": "Use Pythagoras: height² = ladder² - base²",
        "cultural_context": "Pythagoras' theorem is applied in Indian construction of roofs, wells, and stairways.",
        "explanation": "height = √(10² - 6²) = √(100 - 36) = √64 = 8 m.",
    },
]


def seed():
    collection = db.questions

    existing_count = collection.count_documents({})
    if existing_count > 0:
        print(f"Questions collection already has {existing_count} documents. Skipping seed.")
        print("To re-seed, drop the collection first: db.questions.drop()")
        return

    result = collection.insert_many(QUESTIONS)
    print(f"Successfully seeded {len(result.inserted_ids)} questions.")
    print(f"Modules seeded: temple(10), rangoli(10), sabzi_mandi(10), geometry_3d(10), general(10)")


if __name__ == "__main__":
    seed()
    client.close()
